variable "aws_region" {
  type        = string
  description = "The aws region."
}
variable "workspace" {
  type        = string
  description = "The workspace name is used to prefix environments "
}
variable "lambda_function_name" {
  type        = string
  description = "The name of the lambda function corresponding to the directory name in lambdas"
}
variable "environment_variables" {
  type        = map(string)
  description = "All environment variables applied to a lambda generated by this module"
  default     = {}
}
variable "kms_key_deletion_duration" {
  type        = number
  description = "The kms key deletion duration"
}
variable "timeout" {
  type        = number
  description = "Number of seconds after which lambda times out"
  default     = 60
}
variable "memory_size" {
  type        = number
  description = "Amount of memory in MB your Lambda Function can use at runtime"
  default     = 128
}
variable "security_group_ids" {
  type        = list(string)
  description = "The list of security groups assigned to VPC lambdas"
}

variable "subnet_ids" {
  type        = list(string)
  description = "The available subnets that the lambda can be spun up in"
}
